version: "3"

services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - "443:443"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=interPHPandDB
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_PASSWORD=123